name: node-shop-builder

services:
  userdb:
    container_name: userdb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_user:/data/db
    environment:
      - TZ=Asia/Ho_Chi_Minh

  catalogdb:
    image: postgres:17.6-alpine3.22
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=catalog
    ports:
      - "5432:5432"
    volumes:
      - catalogdb_db:/var/lib/postgresql/data
      
  inventorydb:
    image: postgres:17.6-alpine3.22
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=inventory
    ports:
      - "5433:5432"
    volumes:
      - inventory_db:/var/lib/postgresql/data
volumes:
  catalogdb_db:
  inventory_db:
  mongo_user: